#!/bin/bash
# github-tomato-adapter — Reference adapter for tomato using GitHub CLI.
# Meets the driver CLI protocol: stdin JSON, stdout JSON, stderr for logs.
# Requires: gh (GitHub CLI) installed and authenticated.

set -euo pipefail

SUBCOMMAND="${1:-}"

case "$SUBCOMMAND" in
  capabilities)
    echo '["create-task","update-status","fetch-task","create-pr","update-pr","comment-pr","mark-pr-ready","mark-pr-failed"]'
    ;;
  create-task)
    TITLE=$(jq -r '.title // "Untitled task"' /dev/stdin)
    gh issue create --title "$TITLE" --body "$(jq -r '.description // ""' /dev/stdin)" --json number,url
    ;;
  update-status)
    TASK_REF=$(jq -r '.task_ref // ""' /dev/stdin)
    STATUS=$(jq -r '.status // ""' /dev/stdin)
    echo "{\"task_ref\":\"$TASK_REF\",\"status\":\"$STATUS\"}"
    ;;
  fetch-task)
    QUERY=$(jq -r '.query // ""' /dev/stdin)
    gh issue list --search "$QUERY" --json number,title,url
    ;;
  create-pr)
    TITLE=$(jq -r '.title // "tomato PR"' /dev/stdin)
    gh pr create --draft --title "$TITLE" --body "Generated by tomato" --json number,url
    ;;
  update-pr)
    PR_REF=$(jq -r '.pr_ref // ""' /dev/stdin)
    echo "{\"pr_ref\":\"$PR_REF\",\"status\":\"updated\"}"
    ;;
  comment-pr)
    PR_REF=$(jq -r '.pr_ref // ""' /dev/stdin)
    BODY=$(jq -r '.comments // ""' /dev/stdin)
    gh pr comment "$PR_REF" --body "$BODY"
    echo "{\"pr_ref\":\"$PR_REF\",\"status\":\"commented\"}"
    ;;
  mark-pr-ready)
    PR_REF=$(jq -r '.pr_ref // ""' /dev/stdin)
    gh pr ready "$PR_REF"
    echo "{\"pr_ref\":\"$PR_REF\",\"status\":\"ready\"}"
    ;;
  mark-pr-failed)
    PR_REF=$(jq -r '.pr_ref // ""' /dev/stdin)
    gh pr comment "$PR_REF" --body "⛔ **Review Failed**: This PR has blocking issues that could not be resolved automatically."
    gh pr edit "$PR_REF" --add-label "review-failed"
    echo "{\"pr_ref\":\"$PR_REF\",\"status\":\"failed\"}"
    ;;
  *)
    echo "Unknown subcommand: $SUBCOMMAND" >&2
    exit 1
    ;;
esac
