package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "Usage: github-tomato-adapter <subcommand>")
		os.Exit(1)
	}

	subcommand := os.Args[1]

	var input map[string]interface{}
	if needsInput(subcommand) {
		if err := json.NewDecoder(os.Stdin).Decode(&input); err != nil {
			input = map[string]interface{}{}
		}
	} else {
		input = map[string]interface{}{}
	}

	var output interface{}
	var err error

	switch subcommand {
	case "capabilities":
		output = []string{
			"create-task", "update-status", "fetch-task",
			"create-pr", "update-pr", "comment-pr", "mark-pr-ready", "mark-pr-failed",
		}
	case "create-task":
		title := str(input, "title")
		body := str(input, "description")
		output, err = runGh("issue", "create", "--title", title, "--body", body, "--json", "number,url")
	case "update-status":
		output = map[string]string{"task_ref": str(input, "task_ref"), "status": str(input, "status")}
	case "fetch-task":
		output, err = runGh("issue", "list", "--search", str(input, "query"), "--json", "number,title,url")
	case "create-pr":
		body := str(input, "body")
		if body == "" {
			body = "Generated by tomato"
		}
		output, err = createPR(str(input, "title"), body)
	case "update-pr":
		output = map[string]string{"pr_ref": str(input, "pr_ref"), "status": "updated"}
	case "comment-pr":
		output, err = runGh("pr", "comment", str(input, "pr_ref"), "--body", str(input, "comments"))
	case "mark-pr-ready":
		output, err = runGh("pr", "ready", str(input, "pr_ref"))
	case "mark-pr-failed":
		prRef := str(input, "pr_ref")
		runGh("pr", "comment", prRef, "--body", "⛔ **Review Failed**: This PR has blocking issues that could not be resolved automatically.")
		output, err = runGh("pr", "edit", prRef, "--add-label", "review-failed")
	default:
		fmt.Fprintf(os.Stderr, "Unknown subcommand: %s\n", subcommand)
		os.Exit(1)
	}

	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	outJSON, _ := json.Marshal(output)
	fmt.Println(string(outJSON))
}

func str(m map[string]interface{}, key string) string {
	if v, ok := m[key]; ok {
		return fmt.Sprintf("%v", v)
	}
	return ""
}

func needsInput(subcommand string) bool {
	switch subcommand {
	case "capabilities":
		return false
	default:
		return true
	}
}

func createPR(title, body string) (interface{}, error) {
	// gh pr create does not support --json in older gh versions. It prints the
	// created PR URL to stdout, so parse that instead.
	cmd := exec.Command("gh", "pr", "create", "--draft", "--title", title, "--body", body)
	cmd.Env = os.Environ()
	if token := os.Getenv("GITHUB_TOKEN"); token != "" {
		cmd.Env = append(cmd.Env, "GH_TOKEN="+token)
	}
	out, err := cmd.Output()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			return nil, fmt.Errorf("gh pr create failed: %s", string(exitErr.Stderr))
		}
		return nil, err
	}
	return parsePRCreateOutput(string(out)), nil
}

func parsePRCreateOutput(out string) map[string]string {
	url := strings.TrimSpace(out)
	ref := ""
	if idx := strings.LastIndex(url, "/"); idx >= 0 && idx < len(url)-1 {
		ref = url[idx+1:]
	}
	return map[string]string{"pr_ref": ref, "url": url}
}

func runGh(args ...string) (interface{}, error) {
	cmd := exec.Command("gh", args...)
	cmd.Env = os.Environ()
	// If GH_TOKEN is set, use it
	if token := os.Getenv("GITHUB_TOKEN"); token != "" {
		cmd.Env = append(cmd.Env, "GH_TOKEN="+token)
	}
	out, err := cmd.Output()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			return nil, fmt.Errorf("gh %s failed: %s", strings.Join(args, " "), string(exitErr.Stderr))
		}
		return nil, err
	}
	// Try to parse as JSON
	var result interface{}
	if json.Unmarshal(out, &result) == nil {
		return result, nil
	}
	return map[string]string{"output": strings.TrimSpace(string(out))}, nil
}
